# Generated by Django 5.2.7 on 2025-11-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bebidas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bebida",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="bebidas/"),
        ),
        migrations.AlterField(
            model_name="marca",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="marcas/"),
        ),
    ]
